
before_script:
        - apt-get update
        - apt-get install -y libopenblas-base libopenblas-dev
        - apt-get install -y python3-numpy python3-scipy python3-dev python3-setuptools
        - apt-get install -y libfftw3-3 libfftw3-dev check pkg-config
        - git clone https://github.com/DaveGamble/cJSON.git && cd cJSON
        - make
        - make install
        - cd ../
        - ldconfig

build_openblas:
    script:
        - chmod +x bootstrap.sh 
        - ./bootstrap.sh 
        - CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib ./configure --enable-python
        - make
        - OMP_NUM_THREADS=4 make check


