language: c
os:
        - linux
before_install:
        - sudo apt-get update
        
install: 
        - sudo apt-get install -y libopenblas-base libopenblas-dev
        - sudo apt-get install -y python3-numpy python3-scipy python3-dev python3-setuptools
        - sudo apt-get install -y libfftw3-3 libfftw3-dev check pkg-config
        - pkg-config --libs check
        - sudo apt-get install -y libsubunit0
        - dpkg -L libsubunit0
        - git clone https://github.com/DaveGamble/cJSON.git && cd cJSON
        - make
        - sudo make install
        - ls /usr/local/include
        - ls /usr/local/lib
        - cd ../
        - sudo ldconfig

script:
        - chmod +x bootstrap.sh 
        - ./bootstrap.sh 
        - CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib ./configure --enable-python
        - make
        - OMP_NUM_THREADS=4 make check


